apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: alpine
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
  - name: shipa
    image: shipasoftware/cli:v1.3.1-cloud
    command:
    - cat
    tty: true
    volumeMounts:
    - name: shipa-root
      mountPath: /root/.shipa
    - name: shipa-certs
      mountPath: /root/.shipa/certificates
    - name: shipa-tokend
      mountPath: /root/.shipa/token.d
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: shipa-root
    secret:
      secretName: shipa-root
  - name: shipa-certs
    secret:
      secretName: shipa-certs
  - name: shipa-tokend
    secret:
      secretName: shipa-tokend
